### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by pablo67340** [notscimmy/libelevate#1]
Not sure what I am doing wrong, I have c++17 set, win32 platform, and its pointed against the libelevate.lib (both libelevate and libcapcom build successfully) however testelevate always fails to build with the error:  

LNK2019	unresolved external symbol "bool __cdecl grant_access(void *,unsigned long)" (?grant_access@@YA_NPAXK@Z) referenced in function _main

Any chance you might know what the problem is? Would you be able to release a built exe? Is the source outdated? I have been at this for a solid 3 hours now. Any help is appreciated.

**Comment by notscimmy** [comment]
Sounds like you just don't have your linker settings set up properly. Make sure that your "Additional Library Dependencies" points to the path that libelevate.lib lives in.

There should be no problems building and linking this from any visual studio project.

**Comment by notscimmy** [comment]
Closing
